local ADDON = select(2,...)                                 --Includes all functions and variables

local L = LibStub("AceLocale-3.0"):NewLocale(ADDON.name, "enUS", true, ADDON.debug)
if not L then return end

L["additemtoignorelist"] = "Add item to ignore list"
L["addtofav"] = "Add to favorites."
L["alt"] = "ALT"
L["autoloot"] = " (+ Autoloot)"
L["bothfactions"] = "Show CDs und Tradeskills of both factions"
L["cds"] = "Cooldowns"
L["coodownexpired"] = "Coodown Expired!"
L["ctrl"] = "CTRL"
L["databaseempty"] = "Database empty"
L["deletechartooltip"] = "|cffff0000Attention:|r Clears all settings of this character!"
L["deleteignoreditemtooltip"] = "Delete from ignore list"
L["delrealm"] = "Delete all characters on realm!"
L["draenor_jewelcrafting"] = "Draenor Jewelcrafting"
L["favorites"] = "Favorites"
L["filter"] = "Hide tradeskills"
L["ignores"] = "Ignored items"
L["infight"] = "You are in fight!"
L["knowallrecipes"] = "|cffffcf00All recipes already learned|r"
L["leftclick"] = "Left Click"
L["legion_alchemy"] = "Legion Transmutation"
L["linktome"] = "Link to me"
L["linktoother"] = "Link to chat"
L["magnificence"] = "Magnificence"
L["menufontsize"] = "Menu Font Size"
L["nocds"] = "All Ready"
L["nofavorites"] = "No Favorites"
L["nomats"] = "No Mats"
L["openLastProfessionWindow"] = "Open last opened profession window"
L["openmenu"] = "Open Menu"
L["otherchar"] = "Other Characters"
L["pandaria_research"] = "Pandaria research"
L["professions"] = "Professions"
L["quicklaunch"] = "Key combinations (Quickaccess)"
L["quicklauncher"] = "Create separate quicklaunchers"
L["relog"] = "Relog is required!"
L["removefromfav"] = "Remove from favorites."
L["resetcds"] = "Reset CDs"
L["rightclick"] = "Right Click"
L["settings"] = "Settings"
L["shift"] = "Shift"
L["ShowAllTooltips"] = "Show all tooltips"
L["showbuttons"] = "Buttons"
L["showcds"] = "Cooldowns"
L["showcrosscds"] = "Show cross-realm cooldowns"
L["showfavorites"] = "Show Favorites"
L["ShowIfYouCanCraftThisInItemTooltips"] = "Show in item tooltips, if you can craft this."
L["showlastprofinldb"] = "Show last profession on broker display"
L["sphere"] = "Sphere"
L["tooltip_showexpansionname"] = "Show Expansion Name"
L["tooltip_showexpansionranks"] = "Show Expansion Ranks"
L["tooltips"] = "Tooltips"
L["transmute"] = "Transmute"


-- L["addtofav"] = "Add to favorites."
-- L["alt"] = "ALT"
-- L["autoloot"] = " (+ Autoloot)"
-- L["bothfactions"] = "Show CDs und Tradeskills of both factions"
-- L["cds"] = "Cooldowns"
-- L["ctrl"] = "CTRL"
-- L["databaseempty"] = "Database empty"
-- L["deletechartooltip"] = "|cffff0000Attention:|r Clears all settings of this character!"
-- L["draenor_jewelcrafting"] = "Draenor Jewelcrafting"
-- L["favorites"] = "Favorites"
-- L["filter"] = "Hide tradeskills"
-- L["infight"] = "You are in fight!"
-- L["knowallrecipes"] = "|cffffcf00All recipes already learned|r"
-- L["leftclick"] = "Left Click"
-- L["legion_alchemy"] = "Legion Alchemy"
-- L["linktome"] = "Link to me"
-- L["linktoother"] = "Link to chat"
-- L["menufontsize"] = "Menu Font Size"
-- L["nocds"] = "All Ready"
-- L["nofavorites"] = [=[No favorites created!
-- Open tradeskill window and right-click on
-- your tradeskills to create favorites.]=]
-- L["nomats"] = "No Mats"
-- L["openLastProfessionWindow"] = "Open last opened profession window"
-- L["openmenu"] = "Open Menu"
-- L["otherchar"] = "Other Characters"
-- L["pandaria_research"] = "Pandaria research"
-- L["professions"] = "Professions"
-- L["quicklaunch"] = "Key combinations (Quickaccess)"
-- L["quicklauncher"] = "Create separate quicklaunchers"
-- L["relog"] = "Relog is required!"
-- L["removefromfav"] = "Remove from favorites."
-- L["resetcds"] = "Reset CDs"
-- L["rightclick"] = "Right Click"
-- L["settings"] = "Settings"
-- L["shift"] = "Shift"
-- L["ShowAllTooltips"] = "Show all tooltips"
-- L["showbuttons"] = "Buttons"
-- L["showcds"] = "Cooldowns"
-- L["showfavorites"] = "Show Favorites"
-- L["ShowIfYouCanCraftThisInItemTooltips"] = "Show in item tooltips, if you can craft this."
-- L["tooltips"] = "Tooltips"
-- L["trainer"] = "Trainer"
-- L["trainerdisabled"] = "Disable trainer frame"
-- L["transmute"] = "Transmute"
-- L["visityourtrainer"] = "Visit your |cff00ff00%s|r trainer"



